In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [7]:
a = [1, 2, 3]

In [8]:
a

[1, 2, 3]

In [9]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [10]:
np.zeros(5,)

array([0., 0., 0., 0., 0.])

In [11]:
np.c_[1,2,3]

array([[1, 2, 3]], dtype=int32)

In [12]:
array([[1, 2, 3]], dtype=int32)

NameError: name 'array' is not defined

In [13]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [14]:
np.c_[np.array([[1, 2], [3, 4], [5, 6]])]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.c_[np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])]

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [16]:
np.c_[np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]]), np.zeros(4,)]

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [17]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(2,)]

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 2 has size 2

In [19]:
np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)]

array([[1., 4., 0.],
       [2., 5., 0.],
       [3., 6., 0.]])

In [20]:
np.r_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)]

array([1., 2., 3., 4., 5., 6., 0., 0., 0.])

In [21]:
np.append[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)]

TypeError: 'function' object is not subscriptable

In [22]:
np.append(np.array([1,2,3]), np.array([4,5,6]), np.zeros(3))

TypeError: only integer scalar arrays can be converted to a scalar index

In [23]:
np.append(np.array([4,5,6]), np.zeros(3))

array([4., 5., 6., 0., 0., 0.])

In [24]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], np.zeros(3))

array([1., 4., 0., 2., 5., 0., 3., 6., 0., 0., 0., 0.])

In [25]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], np.zeros(3), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [26]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.zeros(3)], axis=0)

array([[1., 4., 0.],
       [2., 5., 0.],
       [3., 6., 0.],
       [0., 0., 0.]])

In [27]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.zeros(1), [1]], axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [28]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.zeros(1), 1, axis=0)

SyntaxError: invalid syntax (<ipython-input-28-1e22f253aa68>, line 1)

In [29]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.zeros(2), [1]], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [30]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.zeros(2), 1], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [31]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.zeros(1)], axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [32]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.zeros(3)], axis=0)

array([[1., 4., 0.],
       [2., 5., 0.],
       [3., 6., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.zeros(3).append(1)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [38]:
np.zeros(3).insert(1)

AttributeError: 'numpy.ndarray' object has no attribute 'insert'

In [44]:
np.insert(np.zeros(3), 0)

TypeError: _insert_dispatcher() missing 1 required positional argument: 'values'

In [49]:
np.append(np.c_[np.array([1,2,3]), np.array([4,5,6]), np.zeros(3)], [np.append(np.zeros(2), [1])], axis=0)

array([[1., 4., 0.],
       [2., 5., 0.],
       [3., 6., 0.],
       [0., 0., 1.]])

In [1]:
np.array([[1, 0], [2, 0], [3, 1]])

NameError: name 'np' is not defined

In [2]:
np.identity(3)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
array = np.identity(3)

In [6]:
array.append([1, 2, 3])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [7]:
np.c_[np.identity(3), [1, 2, 3]]

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.]])

In [8]:
np.c_[np.identity(3), [1, 2, 3]].append([4, 4, 4, 4])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
np.append(np.c_[np.identity(3), [1, 2, 3]], [4, 4, 4, 4])

array([1., 0., 0., 1., 0., 1., 0., 2., 0., 0., 1., 3., 4., 4., 4., 4.])

In [10]:
np.append(np.c_[np.identity(3), [1, 2, 3]], [4, 4, 4, 4], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [11]:
np.append(np.c_[np.identity(3), [1, 2, 3]], np.array([4, 4, 4, 4]), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [12]:
np.vstack(np.c_[np.identity(3), [1, 2, 3]], np.array([4, 4, 4, 4]))

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [13]:
np.vstack[np.c_[np.identity(3), [1, 2, 3]], np.array([4, 4, 4, 4])]

TypeError: 'function' object is not subscriptable

In [14]:
np.vstack([np.c_[np.identity(3), [1, 2, 3]], np.array([4, 4, 4, 4])])

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.],
       [4., 4., 4., 4.]])

In [15]:
[2, 3].shape

AttributeError: 'list' object has no attribute 'shape'

In [16]:
np.array([2, 3]).shape

(2,)

In [17]:
np.array([2, 3, 4]).shape

(3,)

In [18]:
np.array([[2, 3, 3], [1, 1, 1]])shape

SyntaxError: invalid syntax (<ipython-input-18-dd5921f96ee4>, line 1)

In [19]:
np.array([[2, 3, 3], [1, 1, 1]]).shape

(2, 3)

In [20]:
tuple = (1, 2, 3,)

In [21]:
np.asarray(tuple)

array([1, 2, 3])

In [3]:
np.vstack([np.c_[np.identity(3), [1, 2, 3]], np.array([4, 4, 4, 4])])

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.],
       [4., 4., 4., 4.]])

In [2]:
import numpy as np

In [4]:
np.vstack([np.c_[np.identity(3), np.array([-2, 3])], np.array([4, 4, 4, 4])])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [18]:
np.vstack([np.c_[np.identity(shape[0]), t], [np.append(np.zeros(shape[0]), [1])]])

array([[ 1.,  0., -2.],
       [ 0.,  1.,  3.],
       [ 0.,  0.,  1.]])

In [24]:
np.array([
        [np.cos(rad_theta), -np.sin(rad_theta)],
        [np.sin(rad_theta), np.cos(rad_theta)]
    ])

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])